name: Test and push # Nombre del flujo de trabajo

on:
  push:
    branches:
      - develop # Se ejecuta cuando se realiza un push en la rama "develop"

jobs:
  test:
    runs-on: ubuntu-latest # Se ejecuta en una máquina con Ubuntu

    services:
      mongodb:
        image: mongo
        ports:
          - 27017:27017  # DB mongo que se ejecua en el puerto 27017

    steps:
      - name: Checkout code  # Paso para clonar el código fuente del repositorio
        uses: actions/checkout@v2

      - name: Set up Python  # Paso para configurar Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'   # Versión de Python a utilizar

      - name: Install dependencies   # Paso para instalar las dependencias del proyecto
        run: |
          python -m pip install --upgrade pip
          pip install -r Backend/requirements.txt

      - name: Set up environment variables  # seteo variables de entorno configuradas en github
        run: |
          echo "MONGO_URI=${{ secrets.MY_SECRET_VARIABLES }}" >> $GITHUB_ENV
          echo "BASE_URL=${{ secrets.MY_SECRET_VARIABLES }}" >> $GITHUB_ENV
        
      - name: Run tests  # Paso para ejecutar los tests
        run: |
          cd Backend
          python test.py
          if [ $? -ne 0 ]; then exit 1; fi
